# Generated by Django 4.2.19 on 2025-03-10 18:23

import apps.curriculum.models
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_empresa)),
                ('descripcion', models.TextField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_habilidad, verbose_name='Imagen de habilidad')),
                ('tiny', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_habilidad, verbose_name='Imagen de habilidad para móvil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('url_canonical', models.URLField(verbose_name='URL canonical')),
                ('mmeta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=256, null=True)),
                ('og_description', models.CharField(blank=True, max_length=256, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_seo)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_1', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('apellido_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ES', verbose_name='Teléfono')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('web_personal', models.URLField(blank=True, null=True, verbose_name='Web Personal')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_perfil, verbose_name='Imagen de perfil')),
                ('tiny', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_perfil, verbose_name='Imagen de perfil móvil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('url_canonical', models.URLField(verbose_name='URL canonical')),
                ('mmeta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=256, null=True)),
                ('og_description', models.CharField(blank=True, max_length=256, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_seo)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('title', models.CharField(max_length=128)),
                ('url_proyecto', models.URLField(blank=True, null=True, verbose_name='URL del proyecto')),
                ('url_proyecto_demo', models.URLField(blank=True, null=True, verbose_name='URL demo del proeycto')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_proyecto, verbose_name='Imagen de habilidad')),
                ('tiny', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_proyecto, verbose_name='Imagen de habilidad para móvil')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('texto_enriquecido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('habilidades', models.ManyToManyField(to='curriculum.habilidad', verbose_name='Habilidades')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='curriculum.perfil')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='curriculum.perfil'),
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculum.empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculum.perfil')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción')),
                ('thumbnail_titulo', models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_titulo, verbose_name='Imagen del título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulaciones', to='curriculum.perfil')),
            ],
            options={
                'verbose_name': 'Educacion',
                'verbose_name_plural': 'Titulaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
