# Generated by Django 4.2.19 on 2025-03-10 20:04

import datetime
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción del puesto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
