# Generated by Django 4.2.19 on 2025-03-13 21:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_perfil_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='experiencias', to='curriculum.habilidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='texto_enriquecido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto enriquecido'),
        ),
    ]
