# Generated by Django 4.2.19 on 2025-03-17 22:59

import apps.curriculum.models
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_experiencia_habilidades_alter_proyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='mmeta_description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='mmeta_description',
            new_name='meta_description',
        ),
        migrations.AlterField(
            model_name='educacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='texto_enriquecido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto enriquecido'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_proyecto, verbose_name='Imagen de proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tiny',
            field=models.ImageField(blank=True, null=True, upload_to=apps.curriculum.models.upload_to_proyecto, verbose_name='Imagen de proyecto para móvil'),
        ),
    ]
