# Generated by Django 4.2.19 on 2025-03-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_rename_mmeta_description_perfil_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='url_canonical',
            field=models.URLField(blank=True, null=True, verbose_name='URL canonical'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url_canonical',
            field=models.URLField(blank=True, null=True, verbose_name='URL canonical'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url_proyecto_demo',
            field=models.URLField(blank=True, null=True, verbose_name='URL demo del proyecto'),
        ),
    ]
