# Generated by Django 4.2.19 on 2025-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_perfil_url_canonical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='curriculum.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='introduccion',
            field=models.TextField(blank=True, max_length=300, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'Aplicación móvil'), ('desktop', 'Aplicación de escritorio'), ('otro', 'Otro')], default='app', max_length=20, verbose_name='Tipos de proyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
