# Generated by Django 4.2.19 on 2025-03-01 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_visualizaciones_alter_heading_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visualizaciones',
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_view', to='blog.post')),
            ],
        ),
    ]
