import type { ProjectType, BlogPostType } from "./types"

export const projectsData: ProjectType[] = [
  {
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce platform with secure payment processing and user authentication.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["React", "Node.js", "MongoDB", "Stripe"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    title: "Portfolio Website",
    description: "A responsive portfolio website built with Next.js and Tailwind CSS.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    title: "Task Management App",
    description: "A collaborative task management application with real-time updates.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["React", "Firebase", "TypeScript"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    title: "Weather Dashboard",
    description: "A weather dashboard that displays current and forecasted weather data.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["JavaScript", "OpenWeather API", "Chart.js"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    title: "Social Media Dashboard",
    description: "A dashboard for managing and analyzing social media accounts and performance.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Vue.js", "Express", "PostgreSQL"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    title: "AI Image Generator",
    description: "An application that generates images using AI based on text prompts.",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["React", "OpenAI API", "TailwindCSS"],
    demoUrl: "#",
    githubUrl: "#",
  },
]

export const blogPostsData: BlogPostType[] = [
  {
    slug: "getting-started-with-nextjs",
    title: "Getting Started with Next.js: A Comprehensive Guide",
    excerpt: "Learn how to build modern web applications with Next.js, from setup to deployment.",
    date: "April 15, 2023",
    readingTime: 8,
    coverImage: "/placeholder.svg?height=200&width=400",
    tags: ["Next.js", "React", "Web Development"],
    author: {
      name: "John Doe",
      title: "Senior Frontend Developer",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    slug: "mastering-tailwind-css",
    title: "Mastering Tailwind CSS: Tips and Tricks",
    excerpt: "Discover advanced techniques and best practices for building beautiful UIs with Tailwind CSS.",
    date: "March 22, 2023",
    readingTime: 6,
    coverImage: "/placeholder.svg?height=200&width=400",
    tags: ["CSS", "Tailwind", "Design"],
    author: {
      name: "Jane Smith",
      title: "UI/UX Designer",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    slug: "typescript-for-react-developers",
    title: "TypeScript for React Developers",
    excerpt: "Learn how to leverage TypeScript to build more robust React applications with fewer bugs.",
    date: "February 10, 2023",
    readingTime: 10,
    coverImage: "/placeholder.svg?height=200&width=400",
    tags: ["TypeScript", "React", "JavaScript"],
    author: {
      name: "John Doe",
      title: "Senior Frontend Developer",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    slug: "building-accessible-web-apps",
    title: "Building Accessible Web Applications",
    excerpt: "A guide to creating web applications that are accessible to everyone, including users with disabilities.",
    date: "January 5, 2023",
    readingTime: 7,
    coverImage: "/placeholder.svg?height=200&width=400",
    tags: ["Accessibility", "Web Development", "HTML"],
    author: {
      name: "Jane Smith",
      title: "UI/UX Designer",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
]
